/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccountCenter: typeof import('./src/components/AccountCenter.vue')['default']
    AccountEdit: typeof import('./src/components/AccountEdit.vue')['default']
    AccountList: typeof import('./src/components/AccountList.vue')['default']
    AddAccount: typeof import('./src/components/AddAccount.vue')['default']
    AddGood: typeof import('./src/components/addGood.vue')['default']
    Breadcrumb: typeof import('./src/components/Breadcrumb.vue')['default']
    ContainerView: typeof import('./src/components/ContainerView.vue')['default']
    Echarts: typeof import('./src/components/Echarts.vue')['default']
    EditAccountDialog: typeof import('./src/components/EditAccountDialog.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    GoodsList: typeof import('./src/components/GoodsList.vue')['default']
    GoodsType: typeof import('./src/components/GoodsType.vue')['default']
    MenuView: typeof import('./src/components/MenuView.vue')['default']
    OrderList: typeof import('./src/components/OrderList.vue')['default']
    Pagination: typeof import('./src/components/Pagination.vue')['default']
    Person: typeof import('./src/components/Person.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Title: typeof import('./src/components/Title.vue')['default']
  }
}
